id = "moonbit"
name = "MoonBit"
description = "MoonBit language support for Zed, including syntax highlighting and the native LSP server."
version = "0.1.2"
schema_version = 1
authors = ["kaashyapan"]
repository = "https://github.com/kaashyapan/zed-moonbit"

[grammars.moonbit]
repository = "https://github.com/moonbitlang/tree-sitter-moonbit"
commit = "36191d7fe4ec4298c8c1f251af6a82939f8e9a67"

[language_servers.moon-lsp]
name = "moonlsp"
languages = ["MoonBit"]
